### ISSUE TITLE
Can't change toolbar position permanently

### ISSUE THREAD

**Issue by TomNog** [All4Gis/CustomToolBar#3]
Hi Francisco, that's a great tool for a better overview. Thanks! I use it in QGIS 3.6
Let's change the position of a custom toolbar. Then close and restart QGIS. Now the position of this toolbar and even some system toolbars has changed. 
Best wishes, Thomas

**Comment by All4Gis** [comment]
Hi @TomNog ,thanks for your feedbak, but I can't reproduce it, the toolbar is on the same place when restart in my case !can you try it using a clean install (no plugins)? and attach a screenshot maybe.

thanks

**Comment by TomNog** [comment]
OK, I'll find a computer without QGIS and try it using a clean install. This may last some days.

**Comment by TomNog** [comment]
I found out how to have a clean install without new installation: Settings > User Profiles > New Profile ...

I've installed Customize Toolbars without further changes. The toolbars of the former installation have been loaded automatically.
Now I've changed the position of the Select Toolbar to the right side of the window. After restarting QGIS this toolbar appeared at the upper side of the window again and at the right side was a different toolbar (see attached screenshots).

![1 Select Toolbar at right side](https://user-images.githubusercontent.com/23482770/56639578-48c94b80-6671-11e9-99fb-be36d53f5026.png)
![2 Select Toolbar at upper side again](https://user-images.githubusercontent.com/23482770/56639585-4ebf2c80-6671-11e9-8a25-e4d840297d17.png)

**Comment by TomNog** [comment]
After that I've changed the language (settings > options > general > user interface translation). After restarting QGIS all custom toolbars disappeared instead of being active (the first letter of my custom toolbar names is "T"):
![3 Custom Toolbars disappeared after changing language](https://user-images.githubusercontent.com/23482770/56640404-3bad5c00-6673-11e9-88af-a03398c780bd.png)

**Comment by All4Gis** [comment]
thanks for your feedback.

Your select toolbar ,has been created with the plugin?

About translations.

The tools don't have translation. That is, if you create a tool with QGIS in English, it only works with QGIS in English and not in another language.

**Comment by TomNog** [comment]
Yes, the select toolbar and the other toolbars in the third toolbar line are created with the plugin.

**Comment by TomNog** [comment]
That's the content of the custom toolbars:
![4 Defined Custom Toolbars](https://user-images.githubusercontent.com/23482770/56714789-2f3e0780-6736-11e9-964c-fb84510c1bf9.png)
