### ISSUE TITLE
crash on qgis dev

### ISSUE THREAD

**Issue by johansanders** [All4Gis/CustomToolBar#4]
for your information:

activating the plugin in QGIS DEV results in crash 

Stack Trace
PyMethodDef_RawFastCallKeywords :
PyEval_GetFuncDesc :
PyEval_EvalFrameDefault :
PyEval_EvalCodeWithName :
PyFunction_FastCallDict :
PyObject_FastCallDict :
PyObject_Call_Prepend :
PyType_Ready :
PyType_Name :
PyObject_FastCallKeywords :
PyEval_GetFuncDesc :
PyEval_EvalFrameDefault :
PyEval_EvalCodeWithName :
PyFunction_FastCallDict :
PyObject_FastCallDict :
PyObject_Call_Prepend :
PyType_Ready :
PyType_Name :
PyObject_FastCallKeywords :
PyEval_GetFuncDesc :
PyEval_EvalFrameDefault :
PyObject_Call :
PyFunction_FastCallKeywords :
PyEval_GetFuncDesc :
PyEval_EvalFrameDefault :
PyObject_Call :
PyFunction_FastCallKeywords :
PyEval_GetFuncDesc :
PyEval_EvalFrameDefault :
PyObject_Call :
PyFunction_FastCallKeywords :
PyEval_GetFuncDesc :
PyEval_EvalFrameDefault :
PyObject_Call :
PyFunction_FastCallDict :
PyObject_FastCallDict :
PyObject_Call_Prepend :
PyType_Ready :
PyType_Name :
PyObject_FastCallKeywords :
PyEval_GetFuncDesc :
PyEval_EvalFrameDefault :
PyObject_Call :
PyFunction_FastCallKeywords :
PyEval_GetFuncDesc :
PyEval_EvalFrameDefault :
PyObject_Call :
PyFunction_FastCallKeywords :
PyEval_GetFuncDesc :
PyEval_EvalFrameDefault :
PyObject_Call :
PyFunction_FastCallKeywords :
PyEval_GetFuncDesc :
PyEval_EvalFrameDefault :
PyEval_EvalCodeWithName :
PyRun_FileExFlags :
PyRun_StringFlags :
QgsPythonUtils::QgsPythonUtils :
QgsPythonUtils::QgsPythonUtils :
QgsSnappingWidget::metaObject :
QgsSnappingWidget::metaObject :
QgsSnappingWidget::metaObject :
QgsSnappingWidget::metaObject :
QgsSnappingWidget::metaObject :
QgsSnappingWidget::metaObject :
QMetaObject::activate :
QMetaObject::activate :
QStandardItem::setData :
QStandardItem::child :
QStandardItemModel::itemFromIndex :
QStyledItemDelegate::editorEvent :
QAbstractItemView::selectionModel :
QAbstractItemView::edit :
QPersistentModelIndex::QPersistentModelIndex :
TextInputClient::StartPositionTracking :
QgsPresetSchemeColorRamp::clone :
QGIS Info
QGIS Version: 3.11.0-Master
QGIS code revision: 49dcc2c253
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.1.0dev
Running against GDAL: 3.1.0dev
System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.17763

**Comment by All4Gis** [comment]
Thank you for informing! we'll wait for the official version to see if it still fails.
